export const HOUSIE_TEXT = [
  'Son of a gun',
  'One little duck',
  'Goodness me',
  'Murgi chor',
  'Hum paanch',
  'Super sixer',
  'Single hockey stick',
  'Big fat lady',
  'You are mine',
  'A big fat hen',
  'Sexy legs',
  'Monkeys cousin, one dozen',
  'Unlucky for some, lucky for me',
  'Valentine’s Day',
  'Yet to be kissed',
  'Sweet sixteen',
  'Not so sweet',
  'Voting age',
  'Last of the teens',
  'Blind 20',
  'President’s salute',
  'Two little ducks',
  'You and me',
  'Two dozen',
  'Silver Jublee',
  'Republic Day',
  'Gateway to heaven',
  'Duck and its mate',
  'Gin & Wine',
  'Women get flirty',
  'Get up and run',
  'Buckle my shoe',
  'Two little bees',
  'Dil mange more',
  'Flirty wife',
  'Popular size',
  'Lime and lemon',
  'Oversize',
  'Watch your waistline',
  'Naughty 40',
  'Kiss and run',
  'Winnie the pooh',
  'Pain in the knee',
  'Chor chor, all the 4',
  'Halfway there',
  'Up to tricks',
  'Year of Independence',
  'You are not late',
  'Rise and shine',
  'Half a century',
  'Charity begins at 51',
  'Pack of cards',
  'Stuck in a tree',
  'House with a bamboo door',
  'Bunch of 5s',
  'Pick up sticks',
  'Mutiny Year',
  'Make them wait',
  'Just retired',
  'Five dozen',
  'Bakers bun',
  'Turn the screw',
  'Tickle me',
  'Hard core',
  'Old age pension',
  'Chakke pe chakka',
  'Made in heaven',
  'Check your weight',
  'Ulta Pulta',
  'Lucky blind',
  'Bullet with a gun',
  'Lucky 2',
  'A crutch and a flea',
  'Candy store',
  'Diamond Jublee',
  'Lucky six',
  'Two hockey sticks',
  'Heaven’s gate',
  'One more time',
  'Gandhi’s breakfast',
  'Corner shot',
  'Fat lady with a duck',
  'Time for tea',
  'Last of the chors',
  'Staying alive',
  'Between the sticks',
  'Fat lady with a crutch',
  'Two fat ladies',
  'All but one',
  'Top of the house'
];
